### ISSUE TITLE
Server error bei Registrierung

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#196]
Ein Nutzer hat berichtet, dass es nach Erteilen des Consents einen Server-Error 500 erhalten habe, an der Stelle, wo sonst das Registrierformular angezeigt wurde. Er hatte vorher den Text recht gründlich gelesen. Vielleicht ist aufgrund der verstrichenen Zeit die Session wegen einer Zeitüberschreitung zurückgesetzt worden?

Auszug aus demLog:

```
021-03-11 07:22:26,521 WARNING
Forbidden (CSRF cookie not set.): /results

2021-03-11 07:44:03,035 WARNING
Forbidden (CSRF cookie not set.): /results

2021-03-11 07:52:58,276 ERROR
Internal Server Error: /consent/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/project/app/views_consent.py", line 85, in post
    if request.session["consent_forms_to_be_displayed"][0]["consent_type"] != form.cleaned_data["consent_type"]:
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
KeyError: 'consent_forms_to_be_displayed'
2021-03-11 08:01:18,076 ERROR
Internal Server Error: /consent/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/project/app/views_consent.py", line 85, in post
    if request.session["consent_forms_to_be_displayed"][0]["consent_type"] != form.cleaned_data["consent_type"]:
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
KeyError: 'consent_forms_to_be_displayed'

```

**Comment by simon-anders** [comment]
Ob der CSRF-Fehler aus derselben Session stammt ist unklar.
